name: Task-manager
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
      - name: Run tests
        run: make test
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          XDEBUG_MODE: coverage
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/coverage.xml:clover
          debug: true